#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcryptui
Version  : 3.12.2
Release  : 14
URL      : https://download.gnome.org/sources/libcryptui/3.12/libcryptui-3.12.2.tar.xz
Source0  : https://download.gnome.org/sources/libcryptui/3.12/libcryptui-3.12.2.tar.xz
Summary  : UI library for DBUS functions exported by Seahorse
Group    : Development/Tools
License  : GFDL-1.1 GPL-2.0 LGPL-2.0
Requires: libcryptui-bin = %{version}-%{release}
Requires: libcryptui-data = %{version}-%{release}
Requires: libcryptui-lib = %{version}-%{release}
Requires: libcryptui-license = %{version}-%{release}
Requires: libcryptui-locales = %{version}-%{release}
Requires: libcryptui-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gnupg
BuildRequires : gnupg-bin
BuildRequires : gpgme-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gnome-keyring-1)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(sm)
Patch1: build.patch

%description
Libcryptui: Interface components for OpenPGP
libcryptui is a library used for prompting for PGP keys. It's likely that this
library will become deprecated in the near future.

%package bin
Summary: bin components for the libcryptui package.
Group: Binaries
Requires: libcryptui-data = %{version}-%{release}
Requires: libcryptui-license = %{version}-%{release}

%description bin
bin components for the libcryptui package.


%package data
Summary: data components for the libcryptui package.
Group: Data

%description data
data components for the libcryptui package.


%package dev
Summary: dev components for the libcryptui package.
Group: Development
Requires: libcryptui-lib = %{version}-%{release}
Requires: libcryptui-bin = %{version}-%{release}
Requires: libcryptui-data = %{version}-%{release}
Provides: libcryptui-devel = %{version}-%{release}
Requires: libcryptui = %{version}-%{release}

%description dev
dev components for the libcryptui package.


%package doc
Summary: doc components for the libcryptui package.
Group: Documentation
Requires: libcryptui-man = %{version}-%{release}

%description doc
doc components for the libcryptui package.


%package lib
Summary: lib components for the libcryptui package.
Group: Libraries
Requires: libcryptui-data = %{version}-%{release}
Requires: libcryptui-license = %{version}-%{release}

%description lib
lib components for the libcryptui package.


%package license
Summary: license components for the libcryptui package.
Group: Default

%description license
license components for the libcryptui package.


%package locales
Summary: locales components for the libcryptui package.
Group: Default

%description locales
locales components for the libcryptui package.


%package man
Summary: man components for the libcryptui package.
Group: Default

%description man
man components for the libcryptui package.


%prep
%setup -q -n libcryptui-3.12.2
cd %{_builddir}/libcryptui-3.12.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664156779
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1664156779
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcryptui
cp %{_builddir}/libcryptui-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libcryptui/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/libcryptui-%{version}/COPYING-DOCS %{buildroot}/usr/share/package-licenses/libcryptui/c61905dc64311e8bcee6afc425fa40f917a45131 || :
cp %{_builddir}/libcryptui-%{version}/COPYING-LIBCRYPTUI %{buildroot}/usr/share/package-licenses/libcryptui/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f || :
%make_install
%find_lang cryptui

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/seahorse-daemon

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/CryptUI-0.0.typelib
/usr/share/GConf/gsettings/org.gnome.seahorse.recipients.convert
/usr/share/cryptui/ui/seahorse-notify.xml
/usr/share/cryptui/ui/seahorse-pgp-generate.xml
/usr/share/cryptui/ui/seahorse-progress.xml
/usr/share/dbus-1/services/org.gnome.seahorse.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.seahorse.recipients.gschema.xml
/usr/share/pixmaps/cryptui/22x22/seahorse-key-personal.png
/usr/share/pixmaps/cryptui/22x22/seahorse-key-ssh.png
/usr/share/pixmaps/cryptui/22x22/seahorse-key.png
/usr/share/pixmaps/cryptui/22x22/seahorse-person.png
/usr/share/pixmaps/cryptui/22x22/seahorse-sign-bad.png
/usr/share/pixmaps/cryptui/22x22/seahorse-sign-ok.png
/usr/share/pixmaps/cryptui/22x22/seahorse-sign.png
/usr/share/pixmaps/cryptui/48x48/seahorse-key-personal.png
/usr/share/pixmaps/cryptui/48x48/seahorse-key-ssh.png
/usr/share/pixmaps/cryptui/48x48/seahorse-key.png
/usr/share/pixmaps/cryptui/48x48/seahorse-person.png
/usr/share/pixmaps/cryptui/48x48/seahorse-sign-bad.png
/usr/share/pixmaps/cryptui/48x48/seahorse-sign-ok.png
/usr/share/pixmaps/cryptui/48x48/seahorse-sign-unknown.png
/usr/share/pixmaps/cryptui/48x48/seahorse-sign.png
/usr/share/pixmaps/cryptui/scalable/seahorse-key-personal.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-key-ssh.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-key.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-person.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-sign-bad.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-sign-ok.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-sign-unknown.svg
/usr/share/pixmaps/cryptui/scalable/seahorse-sign.svg

%files dev
%defattr(-,root,root,-)
/usr/include/libcryptui/cryptui-key-chooser.h
/usr/include/libcryptui/cryptui-key-combo.h
/usr/include/libcryptui/cryptui-key-list.h
/usr/include/libcryptui/cryptui-key-store.h
/usr/include/libcryptui/cryptui-keyset.h
/usr/include/libcryptui/cryptui.h
/usr/lib64/libcryptui.so
/usr/lib64/pkgconfig/cryptui-0.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libcryptui/ch01.html
/usr/share/gtk-doc/html/libcryptui/home.png
/usr/share/gtk-doc/html/libcryptui/index.html
/usr/share/gtk-doc/html/libcryptui/index.sgml
/usr/share/gtk-doc/html/libcryptui/left-insensitive.png
/usr/share/gtk-doc/html/libcryptui/left.png
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-defines.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-key-chooser.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-key-combo.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-key-list.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-key-store.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-keyset.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui-marshal.html
/usr/share/gtk-doc/html/libcryptui/libcryptui-cryptui.html
/usr/share/gtk-doc/html/libcryptui/libcryptui.devhelp2
/usr/share/gtk-doc/html/libcryptui/right-insensitive.png
/usr/share/gtk-doc/html/libcryptui/right.png
/usr/share/gtk-doc/html/libcryptui/style.css
/usr/share/gtk-doc/html/libcryptui/up-insensitive.png
/usr/share/gtk-doc/html/libcryptui/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcryptui.so.0
/usr/lib64/libcryptui.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcryptui/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f
/usr/share/package-licenses/libcryptui/c61905dc64311e8bcee6afc425fa40f917a45131
/usr/share/package-licenses/libcryptui/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/seahorse-daemon.1

%files locales -f cryptui.lang
%defattr(-,root,root,-)

